---
title: "Salespeople.sa"
author: "yuexili"
date: "11/16/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#read data
```{r}
library(readxl)
library(gdata)
install.packages("readxl")
install.packages("gdata")
require("xlsx")
library(openxlsx)


setwd("/Users/liyuexi/Desktop/omis2392/Salesperson Training Project")
storeinfo=read.csv("Store attributes.csv")
surveydata=read.csv("Survey data.csv")
traincomp12=read_xls("Training Completion FY12.xls",1)
traincomp13=read.xlsx("Training Completion FY13.xlsx",1)
transaction <- read.table("Transaction-HR data FY11-FY14.txt", sep = "\t", header=TRUE)

```

# data cleansing and raw dataset processing 
```{r}
library(dplyr)
install.packages("dplyr")

#survey data divided into two qualitatic group: product and competency 
surveydata$av_friendly<-rowMeans(surveydata[,c("sh1","sh2","sh3","sh4","sh5")],na.rm = TRUE)
surveydata$av_competency <-rowMeans(surveydata[,c("sc1","sc2","sc3","sc4")],na.rm = TRUE)
surveydata$sh1 <- surveydata$sh2  <- surveydata$sh3  <- surveydata$sh4 <-surveydata$sh5 <-  NULL
surveydata$sc1 <- surveydata$sc2  <- surveydata$sc3  <- surveydata$sc4 <-  NULL
surveydata$greetedbinary<- surveydata$jcdiscussedcreditoptionsbinary <- surveydata$informedeventbinary <- surveydata$pressure <- surveydata$store_number<- NULL
surveydata1= surveydata


#processing on the traincomp12 and traincomp13 then join together and create dummies 
traincomp12$Status <-traincomp13$Status<- NULL 

traincomp12<-filter(traincomp12, `Job Name`=="Jewelry Consultant") 
traincomp12$Job.Name<- ifelse(traincomp12$`Job Name`=="Jewelry Consultant", 'JC','other')
traincomp12$`Job Name`<- NULL
traincomp13<-filter(traincomp13, Job.Name=="JC")


names(traincomp12)[names(traincomp12)=='Store #']<-'store_number'
names(traincomp13)[names(traincomp13)=='Store.#']<-'store_number'
names(transaction)[names(transaction)=='sales_assoc_1']<-'EID'

summary(traincomp12)
train1213<- merge(traincomp12,traincomp13, "EID",all=TRUE)
summary(train1213)

train1213$store_number <- ifelse(is.na(train1213$store_number.x), train1213$store_number.y,train1213$store_number.x)

train1213$State <-ifelse(is.na(train1213$State.x),train1213$State.y,train1213$State.x)  

train1213$job.name<-ifelse(is.na(train1213$Job.Name.x),train1213$Job.Name.y,train1213$Job.Name.x)
  
train1213$Category.x<- ifelse(train1213$Category.x=='FT-Reg','FT','PT')
train1213$Category.y<- ifelse(train1213$Category.y=='FT-Reg' | train1213$Category.y=='FT-Temp', 'FT','PT')
train1213$category<- ifelse(is.na(train1213$Category.x),train1213$Category.y,train1213$Category.x)


#create product dummy 1/0 condition of training 
train1213$train_product<- ifelse(train1213$Warranty=='Yes' | train1213$Credit.x=='Yes' | train1213$Warranties=='Yes' | train1213$Credit.y =='Yes' | train1213$Celebrity.Brand== 'Yes' | train1213$Celebration=='Yes' | train1213$Watches=='Yes' |train1213$Color== 'Yes', 1,0)
train1213$train_product <- ifelse(is.na(train1213$train_product),0,train1213$train_product)

#create service dummy 1/0 condition of training 
train1213$train_service <- ifelse(train1213$`Spec. Ev.`=='Yes' | train1213$`Service.&.Selling`=='Yes',1,0)
train1213$train_service <- ifelse(is.na(train1213$train_service),0,train1213$train_service)

summary(train1213)
newtrain1213<- subset(train1213,select=c("EID","store_number","State","category","train_product","train_service","job.name"))
```



```{r}

#followed the steps given from week1
transaction$month_num <- ifelse(transaction$month=='JAN',1,ifelse(transaction$month=='FEB',2,ifelse(transaction$month=='MAR',3,ifelse(transaction$month=='APR',4,ifelse(transaction$month=='MAY',5,ifelse(transaction$month=='JUN',6,ifelse(transaction$month=='JUL',7,ifelse(transaction$month=='AUG',8,ifelse(transaction$month=='SEP',9,ifelse(transaction$month=='OCT',10,ifelse(transaction$month=='NOV',11,12)))))))))))

#create the varibales FY in transaction_merged table 
transaction$FY <-
  ifelse(transaction$month_num<8,transaction$year-1,transaction$year)

summary(transaction)

emploinfo<- subset(transaction,select=c("EID","transaction_id","SA_gender","SA_AssignmentCategory","SA_YearsofService","SA_MartialStatus","SA_RateofPay","SA_Dependent"),rm.na=TRUE)

customerinfo<- subset(transaction,select=c("customer_id","gender","est_income_code","ethnic_code","homeowner_code","length_of_residence","child","net_purchase_amount"),rm.na=TRUE)


agg_transaction<- aggregate(transaction[c("net_purchase_amount")], by=list(transaction$FY,transaction$month_num), mean)
```

#traincomp13 and traincomp12 data cleansing and processing
```{r}
mergetest0<-merge(surveydata1,customerinfo, "customer_id", rm.na=TRUE)
mergetest1<- merge(mergetest0,emploinfo, "transaction_id",rm.na=TRUE)
mergetest2<- merge(mergetest1, newtrain1213, "EID", rm.na=TRUE)
mergetest3<- merge(mergetest2, storeinfo, "store_number", rm.na=TRUE)

library("VIF")
library("usdm")
install.packages("VIF")
install.packages("usdm")
library(dplyr)  

df1=data.frame(mergetest2$purchasetransactionamount,mergetest2$purchasebasketsize,mergetest2$est_income_code,mergetest2$length_of_residence,mergetest2$net_purchase_amount,mergetest2$SA_YearsofService)
cor(df1)
vif(df1)

#simple OLS model 
summary(mergetest3)
survey_friendly<-   lm(av_friendly ~ train_service+ train_product + purchasetransactionamount + purchasebasketsize + factor(gender) + est_income_code + ethnic_code + factor(category)+ homeowner_code + length_of_residence + factor(child)+ net_purchase_amount+ factor(SA_gender) + ST + factor(MallGrade) +MallSalesSF + StoreSqFt +TotalCases +PadCount + factor(MajorCompetitorPresent), data=mergetest3)
summary(survey_friendly)

survey_competency<- lm(av_competency  ~ train_service+ train_product + purchasetransactionamount + purchasebasketsize + factor(gender) + est_income_code + ethnic_code + factor(category)+ homeowner_code + length_of_residence + factor(child)+ net_purchase_amount+ factor(SA_gender) + ST + factor(MallGrade) +MallSalesSF + StoreSqFt +TotalCases +PadCount + factor(MajorCompetitorPresent), data=mergetest3)
summary(survey_competency)


install.packages("lmtest")
library(lmtest)


```


#discard 
```{r}
# traincomp12<-filter(traincomp12, job_jc=='JC')
# summary(traincomp12$Category)
# print(traincomp12$Category)
# traincomp12$job_cate<- ifelse(traincomp12$Category=='FT-Reg','FT','PT')
# traincomp12$Status<- traincomp12$'Job Name'<- NULL
# 
# print(traincomp13$Job.Name)
# traincomp13<-filter(traincomp13,Job.Name=='JC')
# print(traincomp13$Category)
# comp13$job_cate<- ifelse(traincomp13$Category=='FT-Reg' | traincomp13$Category=='FT-Temp', 'FT','PT')
# traincomp13<-filter(traincomp13, Status=='Active')
# traincomp13$Status <-NULL


# names(traincomp12)[names(traincomp12)=='Store #']<-'store_number'
# names(traincomp13)[names(traincomp13)=='Store.#']<-'store_number'
# names(transaction)[names(transaction)=='sales_assoc_1']<-'EID'
# 
# transaction0 <- merge(transaction,traincomp12,"EID")
# merge1transaction <- merge(transaction0,traincomp13,"EID")
# 
# surveydata$av_friendly<-rowMeans(surveydata[,c("sh1","sh2","sh3","sh4","sh5")],na.rm = TRUE)
# surveydata$av_competency <-rowMeans(surveydata[,c("sc1","sc2","sc3","sc4")],na.rm = TRUE)
# surveydata$sh1 <- surveydata$sh2  <- surveydata$sh3  <- surveydata$sh4 <-surveydata$sh5 <-  NULL
# surveydata$sc1 <- surveydata$sc2  <- surveydata$sc3  <- surveydata$sc4 <-  NULL
# surveydata$greetedbinary<- surveydata$jcdiscussedcreditoptionsbinary <- surveydata$informedeventbinary <- surveydata$pressure <- surveydata$store_number<- NULL
# surveydata1= surveydata


merge2tran_survey<- merge(merge1transaction,surveydata1,"transaction_id")


```




#discard 
```{r}
traincomp12$train_product12.q2<- ifelse(traincomp12$Warranty=='Yes', 1,0)
traincomp12$train_product12.q2<- ifelse(traincomp12$Credit=='Yes', traincomp12$train_product12.q2+1, traincomp12$train_product12.q2) #count on product training module situation  #should be used in question 2 

traincomp13$train_product13.q2<- ifelse(traincomp13$Warranties=='Yes',1,0) 
traincomp13$train_product13.q2<-ifelse(traincomp13$Credit=='Yes',traincomp13$train_product13.q2+1,traincomp13$train_product13.q2)
traincomp13$train_product13.q2<-ifelse(traincomp13$Celebrity.Brand=='Yes',traincomp13$train_product13.q2+1,traincomp13$train_product13.q2)
traincomp13$train_product13.q2<-ifelse(traincomp13$Celebration=='Yes',traincomp13$train_product13.q2+1,traincomp13$train_product13.q2)
traincomp13$train_product13.q2<-ifelse(traincomp13$Watches=='Yes',traincomp13$train_product13.q2+1,traincomp13$train_product13.q2)
traincomp13$train_product13.q2<-ifelse(traincomp13$Color=='Yes',traincomp13$train_product13.q2+1,traincomp13$train_product13.q2)
traincomp13$train_product13.q2<-ifelse(traincomp13$Sp..Events=='Yes',traincomp13$train_product13.q2+1,traincomp13$train_product13.q2)    #count on product training module situation # should be used in question 2 
```




